// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";

import { EmmentalCollection$Type } from "./EmmentalCollection";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["EmmentalCollection"]: EmmentalCollection$Type;
    ["contracts/Emmental.sol:EmmentalCollection"]: EmmentalCollection$Type;
  }
}
